Add check for NPM token in build step (#8276)

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -174,6 +174,15 @@ jobs:
           path: ./${{ env.PACKAGE }}/${{ env.TARBALL }}
       - name: Verify size
         run: python scripts/verify_build_size.py npm
+      - name: Check NPM token
+        run: |
+          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_API_TOKEN }}" > $HOME/.npmrc
+          if npm whoami >/dev/null 2>&1; then
+            echo "NPM token is valid: $(npm whoami)"
+          else
+            echo "::error::Invalid or expired NPM token."
+            exit 1
+          fi
 
   npm_publish:
     name: Publish NPM
