Add back ui test

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -167,78 +167,78 @@ jobs:
         with:
           token: ${{ secrets.CODECOV_TOKEN }}
 
-  # ui_test_suite:
-  #   name: ui:${{ matrix.environment }}:${{ matrix.os }}
-  #   needs: [pre_commit, setup, pixi_lock]
-  #   runs-on: ${{ matrix.os }}
-  #   if: needs.setup.outputs.code_change == 'true' || needs.setup.outputs.doc_change == 'true'
-  #   strategy:
-  #     fail-fast: false
-  #     matrix:
-  #       os: ["ubuntu-latest", "macos-latest", "windows-latest"]
-  #       environment: ["test-ui"]
-  #   timeout-minutes: 60
-  #   env:
-  #     PANEL_LOG_LEVEL: info
-  #     OAUTH_COOKIE_SECRET: ${{ secrets.OAUTH_COOKIE_SECRET }}
-  #     OAUTH_ENCRYPTION_KEY: ${{ secrets.OAUTH_ENCRYPTION_KEY }}
-  #     AUTH0_PORT: "5701"
-  #     AUTH0_OAUTH_KEY: ${{ secrets.AUTH0_OAUTH_KEY }}
-  #     AUTH0_OAUTH_SECRET: ${{ secrets.AUTH0_OAUTH_SECRET }}
-  #     AUTH0_OAUTH_EXTRA_PARAMS: ${{ secrets.AUTH0_OAUTH_EXTRA_PARAMS }}
-  #     AUTH0_OAUTH_USER: ${{ secrets.AUTH0_OAUTH_USER }}
-  #     AUTH0_OAUTH_PASSWORD: ${{ secrets.AUTH0_OAUTH_PASSWORD }}
-  #     OKTA_PORT: "5703"
-  #     OKTA_OAUTH_KEY: ${{ secrets.OKTA_OAUTH_KEY }}
-  #     OKTA_OAUTH_SECRET: ${{ secrets.OKTA_OAUTH_SECRET }}
-  #     OKTA_OAUTH_EXTRA_PARAMS: ${{ secrets.OKTA_OAUTH_EXTRA_PARAMS }}
-  #     OKTA_OAUTH_USER: ${{ secrets.OKTA_OAUTH_USER }}
-  #     OKTA_OAUTH_PASSWORD: ${{ secrets.OKTA_OAUTH_PASSWORD }}
-  #   steps:
-  #     - uses: holoviz-dev/holoviz_tasks/pixi_install@v0
-  #       with:
-  #         environments: ${{ matrix.environment }}
-  #       id: install
-  #     - name: Build pyodide wheels
-  #       run: pixi run -e test-ui "python ./scripts/build_pyodide_wheels.py"
-  #     - name: Launch JupyterLab
-  #       shell: pixi run -e test-ui bash -e {0}
-  #       run: |
-  #         jupyter server extension enable panel.io.jupyter_server_extension --sys-prefix
-  #         (jupyter lab --config panel/tests/ui/jupyter_server_test_config.py --port 8887 > /tmp/jupyterlab_server.log 2>&1) &
-  #     - name: Build JupyterLite
-  #       shell: pixi run -e test-ui bash -e {0}
-  #       run: pixi run -e lite lite-build
-  #     - name: Wait for JupyterLab
-  #       uses: ifaxity/wait-on-action@v1.2.1
-  #       with:
-  #         resource: http-get://localhost:8887/lab
-  #         timeout: 180000
-  #     - name: Check if auth should run
-  #       if: '!github.event.pull_request.head.repo.fork'
-  #       run: |
-  #         echo "PANEL_TEST_AUTH=1" >> $GITHUB_ENV
-  #     - name: Test UI
-  #       run: |
-  #         # Create a .uicoveragerc file to set the concurrency library to greenlet
-  #         # https://github.com/microsoft/playwright-python/issues/313
-  #         echo "[run]\nconcurrency = greenlet" > .uicoveragerc
-  #         FAIL="--screenshot only-on-failure --full-page-screenshot --output ui_screenshots --tracing retain-on-failure"
-  #         pixi run -e ${{ matrix.environment }} test-ui --jupyter $COV --cov-config=.uicoveragerc $FAIL
-  #     - uses: actions/upload-artifact@v4
-  #       if: always()
-  #       with:
-  #         name: ui_screenshots_${{ runner.os }}
-  #         path: ./ui_screenshots
-  #         if-no-files-found: ignore
-  #     - name: Stop JupyterLab
-  #       if: always()
-  #       shell: pixi run -e test-ui bash -e {0}
-  #       run: |
-  #         jupyter lab stop 8887 || true
-  #     - uses: codecov/codecov-action@v4
-  #       with:
-  #         token: ${{ secrets.CODECOV_TOKEN }}
+  ui_test_suite:
+    name: ui:${{ matrix.environment }}:${{ matrix.os }}
+    needs: [pre_commit, setup, pixi_lock]
+    runs-on: ${{ matrix.os }}
+    if: needs.setup.outputs.code_change == 'true' || needs.setup.outputs.doc_change == 'true'
+    strategy:
+      fail-fast: false
+      matrix:
+        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
+        environment: ["test-ui"]
+    timeout-minutes: 60
+    env:
+      PANEL_LOG_LEVEL: info
+      OAUTH_COOKIE_SECRET: ${{ secrets.OAUTH_COOKIE_SECRET }}
+      OAUTH_ENCRYPTION_KEY: ${{ secrets.OAUTH_ENCRYPTION_KEY }}
+      AUTH0_PORT: "5701"
+      AUTH0_OAUTH_KEY: ${{ secrets.AUTH0_OAUTH_KEY }}
+      AUTH0_OAUTH_SECRET: ${{ secrets.AUTH0_OAUTH_SECRET }}
+      AUTH0_OAUTH_EXTRA_PARAMS: ${{ secrets.AUTH0_OAUTH_EXTRA_PARAMS }}
+      AUTH0_OAUTH_USER: ${{ secrets.AUTH0_OAUTH_USER }}
+      AUTH0_OAUTH_PASSWORD: ${{ secrets.AUTH0_OAUTH_PASSWORD }}
+      OKTA_PORT: "5703"
+      OKTA_OAUTH_KEY: ${{ secrets.OKTA_OAUTH_KEY }}
+      OKTA_OAUTH_SECRET: ${{ secrets.OKTA_OAUTH_SECRET }}
+      OKTA_OAUTH_EXTRA_PARAMS: ${{ secrets.OKTA_OAUTH_EXTRA_PARAMS }}
+      OKTA_OAUTH_USER: ${{ secrets.OKTA_OAUTH_USER }}
+      OKTA_OAUTH_PASSWORD: ${{ secrets.OKTA_OAUTH_PASSWORD }}
+    steps:
+      - uses: holoviz-dev/holoviz_tasks/pixi_install@v0
+        with:
+          environments: ${{ matrix.environment }}
+        id: install
+      - name: Build pyodide wheels
+        run: pixi run -e test-ui "python ./scripts/build_pyodide_wheels.py"
+      - name: Launch JupyterLab
+        shell: pixi run -e test-ui bash -e {0}
+        run: |
+          jupyter server extension enable panel.io.jupyter_server_extension --sys-prefix
+          (jupyter lab --config panel/tests/ui/jupyter_server_test_config.py --port 8887 > /tmp/jupyterlab_server.log 2>&1) &
+      - name: Build JupyterLite
+        shell: pixi run -e test-ui bash -e {0}
+        run: pixi run -e lite lite-build
+      - name: Wait for JupyterLab
+        uses: ifaxity/wait-on-action@v1.2.1
+        with:
+          resource: http-get://localhost:8887/lab
+          timeout: 180000
+      - name: Check if auth should run
+        if: '!github.event.pull_request.head.repo.fork'
+        run: |
+          echo "PANEL_TEST_AUTH=1" >> $GITHUB_ENV
+      - name: Test UI
+        run: |
+          # Create a .uicoveragerc file to set the concurrency library to greenlet
+          # https://github.com/microsoft/playwright-python/issues/313
+          echo "[run]\nconcurrency = greenlet" > .uicoveragerc
+          FAIL="--screenshot only-on-failure --full-page-screenshot --output ui_screenshots --tracing retain-on-failure"
+          pixi run -e ${{ matrix.environment }} test-ui --jupyter $COV --cov-config=.uicoveragerc $FAIL
+      - uses: actions/upload-artifact@v4
+        if: always()
+        with:
+          name: ui_screenshots_${{ runner.os }}
+          path: ./ui_screenshots
+          if-no-files-found: ignore
+      - name: Stop JupyterLab
+        if: always()
+        shell: pixi run -e test-ui bash -e {0}
+        run: |
+          jupyter lab stop 8887 || true
+      - uses: codecov/codecov-action@v4
+        with:
+          token: ${{ secrets.CODECOV_TOKEN }}
 
   core_test_suite:
     name: core:${{ matrix.environment }}:${{ matrix.os }}
@@ -281,8 +281,7 @@ jobs:
 
   result_test_suite:
     name: result:test
-    needs: [unit_test_suite, core_test_suite, type_test_suite]
-    # needs: [unit_test_suite, ui_test_suite, core_test_suite, type_test_suite]  # HACK: ADD BACK
+    needs: [unit_test_suite, ui_test_suite, core_test_suite, type_test_suite]
     if: always()
     runs-on: ubuntu-latest
     steps:
